version: "3.8"

services:

  configserver:
    image: nguyenhv236/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - nguyenhv

  eurekaserver:
    image: nguyenhv236/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - nguyenhv
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: nguyenhv236/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - nguyenhv
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: nguyenhv236/loans:latest
    mem_limit: 700m
    ports:
      - "8081:8082"
    networks:
      - nguyenhv
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: nguyenhv236/cards:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - nguyenhv
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

networks:
  nguyenhv: